project:
  type: website

website:
  title: "Welcome to my Blog!"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rgrupesh
      - icon: twitter
        href: https://twitter.com/2L8IWUN_
      - icon: linkedin
        href: https://linkedin.com/in/rupeshgelal
      - icon: book-half
        href: https://hashnode.com/@rgrupesh     
format:
  html:
    theme: yeti
    css: styles.css



